name: cn_formatter_arg_rabby
description: "A package for Consignment Note (CN) Number formatting. Developed by ARG RABBI. Features dot-based normalization and length resolution."
version: 1.0.1
homepage: https://github.com/itrabbi24/CN_Formatter_ARG_RABBY
repository: https://github.com/itrabbi24/CN_Formatter_ARG_RABBY

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # No dependencies needed for pure Dart string logic
